import type { Template } from './types';

export const TEMPLATES: Template[] = [
  {
    id: 'meeting-reschedule',
    label: '日程変更',
    category: 'schedule',
    recipient: 'external',
    type: 'schedule',
    subject: '打ち合わせ日程変更のお願い',
    body: '・来週の打ち合わせの日程を変更したい\n・水曜か木曜の午後が都合がいい\n・ご迷惑をおかけして申し訳ない',
  },
  {
    id: 'thank-you-meeting',
    label: 'お礼（打ち合わせ後）',
    category: 'thanks',
    recipient: 'external',
    type: 'thanks',
    subject: '',
    body: '・本日はお時間をいただきありがとうございました\n・提案内容を社内で検討します\n・来週中に回答します',
  },
  {
    id: 'apology-delay',
    label: 'お詫び（納期遅延）',
    category: 'apology',
    recipient: 'external',
    type: 'apology',
    subject: '',
    body: '・納品が予定より3日遅れる\n・原因はシステム障害\n・○月○日までに納品する\n・再発防止策を講じる',
  },
  {
    id: 'inquiry',
    label: '問い合わせ',
    category: 'inquiry',
    recipient: 'external',
    type: 'inquiry',
    subject: '',
    body: '・御社のサービスについて質問がある\n・料金プランの詳細を知りたい\n・デモの手配は可能か',
  },
  {
    id: 'reminder',
    label: '催促',
    category: 'reminder',
    recipient: 'external',
    type: 'reminder',
    subject: '',
    body: '・先週お送りした見積もりの件\n・ご検討状況を確認したい\n・ご不明点があればお知らせください',
  },
  {
    id: 'decline',
    label: 'お断り',
    category: 'decline',
    recipient: 'external',
    type: 'decline',
    subject: '',
    body: '・ご提案いただいた件について\n・社内で検討した結果、今回は見送りたい\n・理由は予算の都合\n・また機会があればお願いしたい',
  },
  {
    id: 'job-thank-you',
    label: '就活お礼',
    category: 'job',
    recipient: 'recruiter',
    type: 'thanks',
    subject: '',
    body: '・本日の面接のお礼\n・御社の事業に強い関心を持った\n・選考結果をお待ちしています',
  },
  {
    id: 'sick-leave',
    label: '体調不良連絡',
    category: 'report',
    recipient: 'boss',
    type: 'report',
    subject: '',
    body: '・体調が悪いので今日は休みたい\n・熱が38度ある\n・明日は出社できると思う\n・急ぎの案件は○○さんに引き継ぎ済み',
  },
];
